<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>[title]</title>
    <meta name="description" value="Where retro meets retro">
    <meta name="og:title" value="[title]" />
    <meta property="twitter:card" content="summary" />
    <meta property="twitter:title" content="[title]" />
    <link rel="stylesheet" href="/static/main.css">
</head>
<body>
<div class="body-wrapper">
    <div class="title-wrapper">
      <h1 class="title">
        [header]
      </h1>
    </div>
    [content]
    <div class="footer-wrapper">
        <div class="footer"></div>
    </div>
    <div class="slogan-wrapper">
        <div class="slogan">
           _                              _
__      __| |__   ___ _ __ ___   _ __ ___| |_ _ __ ___
\ \ /\ / /| '_ \ / _ \ '__/ _ \ | '__/ _ \ __| '__/ _ \
 \ V  V / | | | |  __/ | |  __/ | | |  __/ |_| | | (_) |
  \_/\_/  |_| |_|\___|_|  \___| |_|  \___|\__|_|  \___/
                     _                  _
 _ __ ___   ___  ___| |_ ___   _ __ ___| |_ _ __ ___
| '_ ` _ \ / _ \/ _ \ __/ __| | '__/ _ \ __| '__/ _ \
| | | | | |  __/  __/ |_\__ \ | | |  __/ |_| | | (_) |
|_| |_| |_|\___|\___|\__|___/ |_|  \___|\__|_|  \___/
        </div>
    </div>
</div>
</body>
</html>
