<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>[title]</title>
    <link rel="stylesheet" href="/static/main.css">
</head>
<body>
<div class="body-wrapper">
    <div class="title-wrapper">
      <h1 class="title">
        [header]
      </h1>
    </div>
    [content]
    <div class="footer-wrapper">
        <div class="footer"></div>
    </div>
</div>
</body>
</html>
