<form class="post-form" action="/[board]/thread/[threadId]/reply/" method="POST">
    <div class="line-wrapper">
        <label class="post-form__title" for="newPost">[newPostText]:</label>
    </div>
    <div class="post-form-text-wrapper">
        <div class="post-form-text-inner-wrapper">
            <textarea
                id="newPost"
                name="text"
                rows="8"
                class="post-form__text"
                placeholder="[postText]*"
            ></textarea>
        </div>
    </div>
    <div class="line-wrapper">
        <button class="post-form__reply" type="submit">[replyText]</button>
    </div>
</form>
