<div class="thread-post" id="[id]">
    <div class="line-wrapper">
        <div class="post__nav">
            <span class="post__date post__date--posted">
              <span class="post-date__text">[postedAtText]:</span>
              <span class="post-date__date">[postedAt]</span>
            </span>
            <span class="post__date post__date--updated">
              <span class="post-date__text">[updatedAtText]:</span>
              <span class="post-date__date">[updatedAt]</span>
            </span>
            <a class="post__link" href="[postUrl]">#[id]</a>
        </div>
    </div>
    <div class="post-title-wrapper">
        <h2 class="post__title">[title]</h2>
    </div>
    <div class="post-wrapper">
        <div class="post">[post]</div>
    </div>
</div>
