app = "ascii-chan"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/srv/public/static"
  url_prefix = "/static"

[mounts]
  source = "database"
  destination = "/srv/data/storage"
